version: "3.8"

services:
  fastapi-app:
    image: fatman244/tili-backend:1
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - PORT=8080
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
